nelmio_api_doc:
    documentation:
        info:
            title: API Reproductor de música CONASA
            description: Aquí podrás ver todos los métodos necesarios del webservice
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
